export type {
  Token,
  PlayerPosition,
  TokenRaiderState,
  ShipNavigation,
  ShipHeading,
  CrewMemberId,
  CrewStatus,
  ChestType,
  CrewNeeds,
  CrewMember,
  TreasureChest,
  FirstMateSpeech,
} from "./types.js";

export {
  TIMER_DURATION_MS,
  TOKENS_PER_ROUND,
  TOKEN_BASE_VALUE,
  PLAYER_MOVE_SPEED,
  COLLECT_RADIUS,
  ARENA_SIZE,
  MAX_ROUNDS,
  FTUE_ROUNDS,
  ROUND_BONUS_MULTIPLIER,
  SHIP_MAX_SPEED,
  SHIP_ACCELERATION,
  SHIP_DECELERATION,
  SHIP_TURN_SPEED,
  SHIP_TICK_MS,
  CREW_INITIAL_FOOD,
  CREW_INITIAL_MORALE,
  NEED_DECAY_FOOD_PER_SEC,
  NEED_DECAY_MORALE_PER_SEC,
  CHEST_FOOD_VALUE,
  CHEST_MORALE_VALUE,
  CHEST_SPAWN_COUNT,
  CHEST_COLLECT_RADIUS,
  FIRST_MATE_WARN_THRESHOLD,
  FIRST_MATE_DIRE_THRESHOLD,
  FIRST_MATE_SPEECH_DURATION_MS,
} from "./constants.js";

export { createInitialGameState, createInitialCrew } from "./state.js";
